[package]
name = "mercator"
version = "0.1.0"
authors = ["damody <t1238142000@gmail.com>"]
description = "Mercator projection for WGS84 to 2d zone"
license = "MIT"

include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
